FROM node:22-alpine AS builder

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/express/package.json ./apps/express/package.json

RUN pnpm install --frozen-lockfile

COPY apps/express ./apps/express

ARG DIRECT_URL
ENV DIRECT_URL=$DIRECT_URL

RUN pnpm --filter express exec prisma generate
RUN pnpm --filter express build


FROM node:22-alpine AS runner

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/express/package.json ./apps/express/package.json

RUN pnpm install --prod --frozen-lockfile

COPY --from=builder /app/apps/express/dist ./apps/express/dist

# Prisma runtime files
COPY --from=builder /app/apps/express/prisma ./apps/express/prisma

WORKDIR /app/apps/express

CMD ["pnpm", "start"]