FROM node:22-alpine as builder

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages  ./packages
COPY apps/socket/package.json ./apps/socket/package.json

RUN pnpm install

COPY . .

RUN pnpm --filter socket build


FROM node:22-alpine as runner

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/socket/package.json ./apps/socket/package.json

RUN pnpm install --prod --frozen-lockfile

COPY --from=builder /app/apps/socket/dist ./apps/socket/dist

WORKDIR /app/apps/socket

CMD ["pnpm", "start"]